Correção de testes e melhorias no código
wagoid/busca-cep pull request #3
Opened 2016-12-22 19:29 UTC by luanaltino

2016-12-22 21:42 UTC, StanleySathler commented
Achei válido a inclusão do _.isEmpty(), embora haja algumas controvérsias a respeito da inclusão de uma dependência só para isso ([veja mais sobre isso aqui](http://www.haneycodes.net/npm-left-pad-have-we-forgotten-how-to-program)). Afinal, o ```isNan()``` já garante a maioria das possibilidades.

Agora, não vi utilidade na inclusão do ```getZipCode()``` sendo esta a única funcionalidade da lib. O livro Clean Code, de Robert C. Martin, é claro quanto à inclusão de contexto desnecessário, e penso eu este ser um exemplo de situação a se evitar. Mas isso é relativo. Há profissonais que apoiariam.

Não acho adequado o nome ```getZipCode()```. Afinal, o "ZIP Code" é o que você passa como argumento, e não necessariamente a resposta.

Por fim, válido a mudança de ```var``` para ```const```.

2016-12-22 21:51 UTC, luanaltino commented
Opa, blz @StanleySathler, o nome da função `getZipCode` não foi eu quem criei, eu simplesmente refatorei para o formato do ECMAScript 6 . Outro ponto importante é que os testes do projeto estavam quebrando pq não encontrava a função `zipSearch` no arquivo index.js.
Se quiser podemos alterar o nome da função para o que você achar víavel no contexto

2016-12-22 21:58 UTC, StanleySathler commented
Oi @luanaltino 

Com relação ao nome, eu sei, mas fica a oportunidade para mudar, hehe. Não foi bem uma crítica, mas uma sugestão para aproveitar o pull. Seguindo os mesmos conceitos do Clean Code, acho que seria bom algo como ```getByZipCode()``` (porque a preposição "by" indica que o ZIP é o argumento, e não a resposta). Ou até mesmo um ```getDetailsByZipCode()```, mas o nome cresce bastante e também há quem não apoie. Isso ficaria a critério do dono do repositório.

E eu imaginei que parte da refatoração pudesse ter sido oriunda do fato de algo não ter dado certo com você. Nesses casos, fica o conselho: explique no commit ou até mesmo na descrição do pull request. Assim, podemos sempre saber o porquê (do contrário, em alguns casos pensamos: "ah, é capricho") e, em algumas situações, aprender com isso.

2016-12-22 22:02 UTC, wagoid commented
@luanaltino a função anterior do módulo estava no `module.exports`, ou seja, era o export padrão do pacote. E Como assim os testes estavam quebrando? Eu não subo versão com teste quebrando, o travis n deixa 😃

2016-12-22 22:04 UTC, wagoid commented on package.json
> +  "version": "0.3.6",
Você poderia retornar a versão? Eu faço a alteração da versão quando subo a tag :)

2016-12-22 22:08 UTC, luanaltino commented on package.json
> +  "version": "0.3.6",
opa, blz, altero sim

2016-12-23 09:50 UTC, wagoid requested changes

2016-12-23 09:50 UTC, wagoid commented on index.js
> +  if (!_.isEmpty(cep) && isNaN(cep)) {
@luanaltino Só falta retornar isso aqui pro que era antes e morreu 😃 
Podemos manter o novo nome da função:
```javascript
module.exports = function getDetailsByZipCode(cep, sync) {
  if (!_.isEmpty(cep) && isNaN(cep)) {
    cep = cep.replace(/[-\s]/g, '');
  }
  ...
  
}
```

Lembrando que você terá que voltar o código dos testes para a forma anterior, senão vai dar pau em tudo 😄

2016-12-23 16:15 UTC, wagoid commented
Nice! Merjando 🚀

2016-12-23 16:15 UTC, merged