Acrescentando opção para setar timeout no request
wagoid/busca-cep pull request #6
Opened 2018-06-11 12:54 UTC by luanaltino

* foi acrescentando um objeto options como terceiro parâmetro da função, nele poderá ser atribuído o valor do timeout do request 
* foi atualizado o readme

2018-06-15 20:26 UTC, wagoid requested changes
Obrigado pela contribuição @luanaltino!
Apenas uma alteração antes de podermos merjar 😃

2018-06-15 20:26 UTC, wagoid commented on index.js
> +module.exports = function getDetailsByZipCode (cep, sync, options) {
Aqui acredito que não precisamos de um terceiro parâmetro, pois o segundo parâmetro já é um objeto
Você poderia trocar para o seguinte:
```
module.exports = function getDetailsByZipCode (cep, options) {
  if (!_.isEmpty(cep) && isNaN(cep)) {
    cep = cep.replace(/[-\s]/g, '');
  }
  return (options === true || (options && options.sync)) ?
    getDataSync(cep, options) :
    getDataAsync(cep, options);
};
```

Dessa forma a pessoa pode chamar `buscaCep('01001-000', true)` ou `buscaCep('01001-000', { sync: true, timeout: 1000 })`

2018-06-15 20:29 UTC, luanaltino commented on index.js
> +module.exports = function getDetailsByZipCode (cep, sync, options) {
Opa, concordo plenamente rs, eu ia fazer assim, só não fiz para não quebrar a versão atual. Vou fazer a alteração aqui e subo jaja

2018-06-15 20:50 UTC, luanaltino commented
@wagoid fiz a alteração, o travis falhou, mas deu timeout num cenário de teste, consegue fazer o rebuild?

2018-07-08 21:47 UTC, wagoid approved these changes
@luanaltino desculpa a demora, estou meio agarrado ultimamente. PR aprovado! :heavy_check_mark:

2018-07-08 22:48 UTC, merged

2018-07-09 15:35 UTC, luanaltino commented
boa @wagoid, :fist_oncoming: